### ISSUE TITLE
Move action

### ISSUE THREAD

**Issue by GAIGResearch** [GAIGResearch/Tribes#132]
Rider (yellow tribe) is not allowed to move as much as it can really do. It happens already on the starting position of the test map, where it should be able to move to two tiles in any plain (no mountain or water) direction

**Comment by GAIGResearch** [comment]
The bugfix in Pathfinder (root -> node), already in master branch, allows the rider to move more... but when the action is executed I see the following exception:

Exception in thread "main" java.lang.NullPointerException
	at core.actions.unitactions.Move.isFeasible(Move.java:31)
	at core.actions.unitactions.Move.execute(Move.java:39)
	at core.game.GameState.next(GameState.java:249)
	at core.game.Game.processTurn(Game.java:234)
	at core.game.Game.tick(Game.java:193)
	at core.game.Game.run(Game.java:168)
	at Run.runGame(Run.java:28)
	at Play.main(Play.java:46)

Reason for the crash: In Move.isFeasible(), tp.findPathTo(destination) is NULL

**Comment by GAIGResearch** [comment]
To be tested:

- [ ] Roads
- [ ] Zone of Influence 
- [ ] Ending movement at a tile with another unit?

**Comment by stevemman** [comment]
As I am testing I plan to write a page in our Wiki that will showcase how movement works in Tribes, similar to this one [https://polytopia.fandom.com/wiki/Movement_guide](url)
