### ISSUE TITLE
Strange attack bug

### ISSUE THREAD

**Issue by GAIGResearch** [GAIGResearch/Tribes#184]
Attacking with a Rider an enemy warrior located in the attacker's capital: **converts** the defender into a unit of the attacker's tribe (???).

Few turns later, it crashed (although defender's tribe had no more units in the game, the crash may have been caused because of that):

Exception in thread "main" java.lang.NullPointerException
	at core.game.Game.endTurn(Game.java:371)
	at core.game.Game.processTurn(Game.java:274)
	at core.game.Game.tick(Game.java:195)
	at core.game.Game.run(Game.java:170)
	at Run.runGame(Run.java:28)
	at Play.play(Play.java:50)
	at Play.main(Play.java:23)

I tried this with:
String filename = "SampleLevel2p.csv";
play(filename, new boolean[]{true,true}, new Types.TRIBE[] {IMPERIUS, OUMAJI});
(in Play.java)

**Comment by GAIGResearch** [comment]
This is actually a Convert issue, only mind benders can execute this action.
