### ISSUE TITLE
Save-load issue, crash on Loading (cast unit -> city)

### ISSUE THREAD

**Issue by GAIGResearch** [GAIGResearch/Tribes#249]
A rider unit is trying to be case into a city. See exception below and json file attached:

[game.txt](https://github.com/GAIGResearch/Tribes/files/4568448/game.txt)

Game seed: 1588441574160, random seed: 1588441574160
Exception in thread "main" java.lang.ClassCastException: core.actors.units.Rider cannot be cast to core.actors.City
	at core.game.Board.getCityInBorders(Board.java:536)
	at core.actors.Tribe.clearView(Tribe.java:204)
	at core.game.Board.moveUnit(Board.java:427)
	at core.actions.unitactions.Move.execute(Move.java:54)
	at core.game.GameState.advance(GameState.java:288)
	at players.osla.OneStepLookAheadAgent.act(OneStepLookAheadAgent.java:49)
	at core.game.Game.processTurn(Game.java:307)
	at core.game.Game.tick(Game.java:225)
	at core.game.Game.run(Game.java:187)
	at Run.runGame(Run.java:28)
	at Play.play(Play.java:77)
	at Play.main(Play.java:45)

**Comment by rovenr12** [comment]
Hi, I use the new method to deal with saving city and unit and also save the information about actorCount in the game.json.

**Comment by GAIGResearch** [comment]
I merged https://github.com/GAIGResearch/Tribes/pull/250
Should this issue be closed?

**Comment by rovenr12** [comment]
I look at the error and it said it happens in getCityInBorders. but when I check the board.citestiles. They are all cityID.

**Comment by GAIGResearch** [comment]
It seems that the exception is thrown is in this line:

return (City) gameActors.get(tileCityId[x][y]);

it's probably loading a Unit with a cityID as actorId in gameActors. It could be the saving process what did it wrong (so the json is incorrect) or loading, not sure what.

I thought your PR https://github.com/GAIGResearch/Tribes/pull/250 was a fixed for this, but maybe not?

**Comment by rovenr12** [comment]
Yep, #250 is to fix this issue. Rather than save the unit and city by board info, the unit and city are saved based on tribe now

**Comment by GAIGResearch** [comment]
Ok, thanks. I'll close the issue now and will open new ones if needed!
